### ISSUE TITLE
support for earlier versions of macOS?

### ISSUE THREAD

**Issue by pleasejustgo** [marcowindt/ds4macos#1]
Firstly, thanks for this! I've been looking for something like this for a long time. And I love the name lol. The problem is... I can't run it! Trying to run the app, I get "...this application requires macOS 11 or later". Any chance for Mojave and higher support? Thanks.

**Comment by forrany** [comment]
yeah, the same issue, hope to support the earlier versions please!!!

**Comment by marcowindt** [comment]
Hi! 
Currently the application uses SwiftUI for the user interface. Unfortunately, [SwiftUI](https://developer.apple.com/documentation/swiftui/) is only supported for Mac OS 10.15+ (Catalina). 

I created a branch in this repo [macOScatalina](https://github.com/marcowindt/ds4macos/tree/macOScatalina) which contains a version of the project that has support for Mac OS 10.15+. Only drawback of this version is that it doesn't support the PS button on DualShock 4 controllers.
