### ISSUE TITLE
Xcode won't open ds4macos file

### ISSUE THREAD

**Issue by pingu17black** [marcowindt/ds4macos#18]
I've downloaded the most recent ds4macos file, opened it within Xcode but then I get this pop up. Working on a MacBook Air with the M1 chip on version 12.6 of macOS Monterey.

<img width="1109" alt="Screenshot 2022-09-24 at 11 31 09" src="https://user-images.githubusercontent.com/114288703/192093183-115c39c4-11f6-45bc-b60c-31bb932f4713.png">

**Comment by marcowindt** [comment]
The `ds4macos.app` file should just launch the app, it's not supposed to be opened with Xcode. If you want to open the project in Xcode open the `ds4macos.xcodeproj` file.
