### ISSUE TITLE
Doesn't Connect to Dolphin

### ISSUE THREAD

**Issue by lbibass** [marcowindt/ds4macos#6]
I'm not sure what's going on, but checking in the xcode log I get this error message. Dolphin connects to DS4MacOS for a few moments, but then disconnects. 

```Got an error sending controller data: POSIXErrorCode: Connection refused```

**Comment by bonylimas** [comment]
I am having the same problem. Using Big Sur 11.6 and Xcode 13.1. Set to release does not make any difference.

`ncoming data request packet: 44535543e9030c00c9af1735d90b4f21020010000100000000000000
New client connection: 192.168.1.111:54241
Got an error sending controller data: POSIXErrorCode: Connection refused
Connection: 🛑 cancelled
Got an error sending controller data: POSIXErrorCode: Operation canceled
Got an error sending controller data: POSIXErrorCode: Connection refused
Connection: 🛑 cancelled
Got an error sending controller data: POSIXErrorCode: Operation canceled
📞📞📞 NWConnection Handler called 
Connection: ✅ ready
Received: Message Type: PORTS
📞📞📞 NWConnection Handler called 
Connection: ✅ ready
Received: Message Type: DATA
Incoming data request packet: 44535543e9030c00cb484e2e56e1e0d7020010000100000000000000
New client connection: 192.168.1.111:52092
Got an error sending controller data: POSIXErrorCode: Connection refused
Got an error sending controller data: POSIXErrorCode: Connection refused
Connection: 🛑 cancelled
👂🏼👂🏼👂🏼 NWListener Handler called
Listener: 🛑 Cancelled by myOffButton`

**Comment by gnarlings** [comment]
Having the exact same issue

```📞📞📞 NWConnection Handler called 
Connection: ✅ ready
Received: Message Type: PORTS
📞📞📞 NWConnection Handler called 
Connection: ✅ ready
Received: Message Type: DATA
Incoming data request packet: 44535543e9030c00a20161de3fa678c8020010000100000000000000
New client connection: 127.0.0.1:61061
Got an error sending controller data: POSIXErrorCode: Connection refused
Connection: 🛑 cancelled
📞📞📞 NWConnection Handler called 
Connection: ✅ ready
Received: Message Type: DATA
Incoming data request packet: 44535543e9030c00a20161de3fa678c8020010000100000000000000
New client connection: 127.0.0.1:49526
Got an error sending controller data: POSIXErrorCode: Connection refused
Connection: 🛑 cancelled

**Comment by AdityaJS12321** [comment]
Any fix for this? The client keeps disconnecting from the server.

**Comment by marcowindt** [comment]
See #8.
