### ISSUE TITLE
Does not work in background

### ISSUE THREAD

**Issue by marcowindt** [marcowindt/ds4macos#7]
When the app is in the background controller input is not processed and send to Dolphin. This is due to the GCController framework which does not allow this. A [solution](https://developer.apple.com/forums/thread/668828), although inconvenient, would be to switch to IOKit.HID framework which does allow running in the background.

**Comment by adityajs12321** [comment]
@marcowindt I think the boolean value `shouldMonitorBackgroundEvents` (part of the GCController framework) should let the app forward inputs from the game controller even when in the background.

**Comment by marcowindt** [comment]
Ah you are absolutely right, thanks! Apparently the [default setting](https://developer.apple.com/documentation/gamecontroller/gccontroller/3738171-shouldmonitorbackgroundevents) changed since MacOS 11.3. I will release a new version with this fix.
